Repository everyones-lck/lck-server, pull requests merged in 2024-07, with the labels that each got.

#4 [Feat/#1] entity setting
  src/main/java/com/lckback/lckforall/LckForAllApplication.java
  src/main/java/com/lckback/lckforall/base/model/BaseEntity.java
  src/main/java/com/lckback/lckforall/base/type/PlayerRole.java
  src/main/java/com/lckback/lckforall/base/type/UserRole.java
  src/main/java/com/lckback/lckforall/base/type/UserStatus.java
  src/main/java/com/lckback/lckforall/community/model/Comment.java
  src/main/java/com/lckback/lckforall/community/model/Post.java
  src/main/java/com/lckback/lckforall/community/model/PostFile.java
  src/main/java/com/lckback/lckforall/community/model/PostType.java
  src/main/java/com/lckback/lckforall/match/model/Match.java
  src/main/java/com/lckback/lckforall/match/model/Set.java
  src/main/java/com/lckback/lckforall/player/model/Player.java
  src/main/java/com/lckback/lckforall/report/model/CommentReport.java
  src/main/java/com/lckback/lckforall/report/model/PostReport.java
  src/main/java/com/lckback/lckforall/team/model/Team.java
  src/main/java/com/lckback/lckforall/user/model/User.java
  src/main/java/com/lckback/lckforall/viewing/model/Participate.java
  src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
  src/main/java/com/lckback/lckforall/vote/model/MatchPogVote.java
  src/main/java/com/lckback/lckforall/vote/model/MatchVote.java
  src/main/java/com/lckback/lckforall/vote/model/SetPogVote.java
Labels: :sparkles: Feature

#8 👷 [CI/#7] CI Test 관련 Github actions 주석 처리
  .github/workflows/CI.yml
  build.gradle
Labels: :tada: CI/CD

#15 [Feat/#6] swagger setting
  build.gradle
  src/main/java/com/lckback/lckforall/base/setting/SwaggerConfig.java
Labels: :sparkles: Feature

#17 [Feat/#16] : 스웨거 활용 예시 구현
  src/main/java/com/lckback/lckforall/viewing/ViewingController.java
Labels: :sparkles: Feature

#13 [Feat/#11] add RestApiException with ErrorCode
  src/main/java/com/lckback/lckforall/base/api/ApiResponse.java
  src/main/java/com/lckback/lckforall/base/api/error/CommonErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/ErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/exception/RestApiException.java
Labels: :sparkles: Feature

#26 [Docs/#14] add pull request template
  .github/pull_request_template.md
Labels: :memo: documentation

#31 [Refactor#28] fix team and player entity
  src/main/java/com/lckback/lckforall/base/type/PlayerPosition.java
  src/main/java/com/lckback/lckforall/match/model/Match.java
  src/main/java/com/lckback/lckforall/match/model/Set.java
  src/main/java/com/lckback/lckforall/player/model/Player.java
  src/main/java/com/lckback/lckforall/player/model/SeasonTeamPlayer.java
  src/main/java/com/lckback/lckforall/team/model/Season.java
  src/main/java/com/lckback/lckforall/team/model/SeasonTeam.java
  src/main/java/com/lckback/lckforall/team/model/Team.java
Labels: :recycle: Refactoring

#30 [Feat#29] about lck match information
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckMatchController.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/AboutMatchConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/FindMatchesByDateDto.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/MatchRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
  src/main/java/com/lckback/lckforall/base/type/MatchResult.java
  src/main/java/com/lckback/lckforall/match/model/Match.java
Labels: :sparkles: Feature, :recycle: Refactoring
