Repository everyones-lck/lck-server, pull requests merged in 2024-08, with the labels that each got.

#38 [Feat/#19] about lck team informantion
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckMatchController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckTeamController.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/FindTeamPlayerHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/FindTeamRatingBySeasonConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/FindTeamRatingHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/FindTeamWinningHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/FindTeamPlayerHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/FindTeamRatingBySeasonDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/FindTeamRatingHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/FindTeamWinningHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/SeasonRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/SeasonTeamRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/TeamRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
Labels: :sparkles: Feature

#44 [Fix/#43]: add annotations
  src/main/java/com/lckback/lckforall/mypage/dto/GetUserProfileDto.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
Labels: :hammer: Fix

#46 [Feat/#39] about lck player information
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckMatchController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckPlayerController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckTeamController.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/player/FindPlayerTeamHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/player/FindPlayerWinningHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamRatingBySeasonConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamRatingHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamWinningHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/player/FindPlayerInformationDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/player/FindPlayerTeamHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/player/FindPlayerWinningHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamPlayerHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamRatingBySeasonDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamRatingHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamWinningHistoryDto.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/PlayerRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/SeasonTeamPlayerRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/SeasonTeamRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckPlayerService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
Labels: :sparkles: Feature

#42 [Feat/#23] error handling
  src/main/java/com/lckback/lckforall/base/api/handler/ExceptionAdvice.java
Labels: :sparkles: Feature

#48 [Feat/#25] home page
  src/main/java/com/lckback/lckforall/match/controller/HomeController.java
  src/main/java/com/lckback/lckforall/match/controller/MatchController.java
  src/main/java/com/lckback/lckforall/match/controller/PogController.java
  src/main/java/com/lckback/lckforall/match/dto/MatchInfoDto.java
  src/main/java/com/lckback/lckforall/match/repository/MatchRepository.java
  src/main/java/com/lckback/lckforall/match/service/HomeService.java
  src/test/java/com/lckback/lckforall/match/HomeServiceTest.java
Labels: :sparkles: Feature

#51 [Feat/#33] update user's profile
  src/main/java/com/lckback/lckforall/base/api/error/UserErrorCode.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/dto/UpdateUserProfileDto.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
  src/main/java/com/lckback/lckforall/user/respository/UserRepository.java
Labels: :sparkles: Feature

#53 [Feat/#35] withdraw from user account
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
  src/main/java/com/lckback/lckforall/user/model/User.java
Labels: :sparkles: Feature

#64 [Refactor#60] repository package path and delete duplicated
  src/main/java/com/lckback/lckforall/aboutlck/repository/MatchRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/repository/PlayerRepository.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckPlayerService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
  src/main/java/com/lckback/lckforall/match/service/PogService.java
  src/main/java/com/lckback/lckforall/player/repository/PlayerRepository.java
  src/main/java/com/lckback/lckforall/player/repository/SeasonTeamPlayerRepository.java
  src/main/java/com/lckback/lckforall/team/repository/SeasonRepository.java
  src/main/java/com/lckback/lckforall/team/repository/SeasonTeamRepository.java
  src/main/java/com/lckback/lckforall/team/repository/TeamRepository.java
  src/test/java/com/lckback/lckforall/match/PogServiceTest.java
Labels: :recycle: Refactoring

#59 [Feat/#57] : 뷰잉파티 개최 API 구현
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java
  src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeService.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
Labels: :sparkles: Feature

#67 [Feat/#66] about lck player information by team
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckTeamController.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerInformationConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamPlayerInformationDto.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
  src/main/java/com/lckback/lckforall/player/repository/SeasonTeamPlayerRepository.java
  src/main/java/com/lckback/lckforall/team/repository/SeasonTeamRepository.java
Labels: :sparkles: Feature

#58 [Feat/#20] login signup
  build.gradle
  src/main/java/com/lckback/lckforall/base/api/error/UserErrorCode.java
  src/main/java/com/lckback/lckforall/base/auth/controller/AdminController.java
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/converter/AuthResponseConverter.java
  src/main/java/com/lckback/lckforall/base/auth/dto/AuthResponseDto.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTUtil.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/TokenService.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
  src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java
  src/main/java/com/lckback/lckforall/base/config/redis/RedisConfig.java
  src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java
  src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java
  src/main/java/com/lckback/lckforall/user/model/User.java
  src/main/java/com/lckback/lckforall/user/respository/UserRepository.java
Labels: :memo: documentation, :sparkles: Feature

#65 [Feat/#54] update my team
  src/main/java/com/lckback/lckforall/base/api/error/TeamErrorCode.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/dto/UpdateMyTeamDto.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
  src/main/java/com/lckback/lckforall/user/model/User.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
Labels: :sparkles: Feature

#71 [Feat/#70] get user post and comment
  src/main/java/com/lckback/lckforall/community/repository/CommentRepository.java
  src/main/java/com/lckback/lckforall/community/repository/PostRepository.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/dto/GetUserCommentDto.java
  src/main/java/com/lckback/lckforall/mypage/dto/GetUserPostDto.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
Labels: :sparkles: Feature

#73 [Feat/#24] today's match vote api 구현
  src/main/java/com/lckback/lckforall/base/api/error/VoteErrorCode.java
  src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java
  src/main/java/com/lckback/lckforall/match/model/Match.java
  src/main/java/com/lckback/lckforall/match/repository/SetRepository.java
  src/main/java/com/lckback/lckforall/player/repository/PlayerRepository.java
  src/main/java/com/lckback/lckforall/team/repository/SeasonTeamRepository.java
  src/main/java/com/lckback/lckforall/vote/controller/VoteController.java
  src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java
  src/main/java/com/lckback/lckforall/vote/dto/SetVoteDto.java
  src/main/java/com/lckback/lckforall/vote/repository/MatchPogVoteRepository.java
  src/main/java/com/lckback/lckforall/vote/repository/MatchVoteRepository.java
  src/main/java/com/lckback/lckforall/vote/repository/SetPogVoteRepository.java
  src/main/java/com/lckback/lckforall/vote/service/VoteService.java
Labels: :sparkles: Feature

#69 [Feat/#61] 뷰잉파티 글 수정/삭제 API 구현
  src/main/java/com/lckback/lckforall/base/api/error/ViewingPartyErrorCode.java
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java
  src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java
  src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
  src/main/java/com/lckback/lckforall/viewing/repository/ViewingPartyRepository.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeService.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyServiceImpl.java
Labels: :sparkles: Feature

#76 [Feat/#62] get participant list
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingController.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyService.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyServiceImpl.java
  src/test/java/com/lckback/lckforall/match/MatchServiceTest.java
Labels: :sparkles: Feature

#78 Refactor/#24 today match vote
  src/main/java/com/lckback/lckforall/base/api/error/VoteErrorCode.java
  src/main/java/com/lckback/lckforall/base/type/PlayerRole.java
  src/main/java/com/lckback/lckforall/match/dto/PogInfoDto.java
  src/main/java/com/lckback/lckforall/match/model/Match.java
  src/main/java/com/lckback/lckforall/match/service/PogService.java
  src/main/java/com/lckback/lckforall/player/repository/PlayerRepository.java
  src/main/java/com/lckback/lckforall/vote/service/VoteService.java
Labels: :recycle: Refactoring

#72 [Refactor/#68] refactor login and signup
  src/main/java/com/lckback/lckforall/base/api/error/TokenErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/UserErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/handler/ExceptionAdvice.java
  src/main/java/com/lckback/lckforall/base/auth/controller/AdminController.java
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/dto/GetKakaoUserIdDto.java
  src/main/java/com/lckback/lckforall/base/auth/dto/GetRefreshTokenDto.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTUtil.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/TokenService.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/model/RefreshToken.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/repository/RefreshTokenRepository.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
  src/main/java/com/lckback/lckforall/base/config/CustomAccessDeniedHandler.java
  src/main/java/com/lckback/lckforall/base/config/CustomAuthenticationEntryPoint.java
  src/main/java/com/lckback/lckforall/base/config/CustomAuthenticationToken.java
  src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java
  src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java
  src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java
  src/main/java/com/lckback/lckforall/user/respository/UserRepository.java
Labels: :sparkles: Feature, :recycle: Refactoring

#82 [Refactor/#81] apply jwt on my page
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
Labels: :sparkles: Feature

#83 [Refactor] 토큰 추가에 따른 로직 변경
  src/main/java/com/lckback/lckforall/vote/controller/VoteController.java
  src/main/java/com/lckback/lckforall/vote/dto/MatchVoteDto.java
  src/main/java/com/lckback/lckforall/vote/dto/SetVoteDto.java
  src/main/java/com/lckback/lckforall/vote/service/VoteService.java
Labels: :recycle: Refactoring

#84 [Feat/#34] logout
  src/main/java/com/lckback/lckforall/base/api/error/TokenErrorCode.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
Labels: :sparkles: Feature

#87 [Feat/#85] s3
  build.gradle
  src/main/java/com/lckback/lckforall/base/api/error/S3ErrorCode.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
  src/main/java/com/lckback/lckforall/base/config/S3Config.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
  src/main/java/com/lckback/lckforall/s3/service/S3Service.java
  src/main/java/com/lckback/lckforall/user/model/User.java
Labels: :sparkles: Feature

#88 [Refactor#80]: modify code related swagger
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java
  src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java
  src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java
Labels: :recycle: Refactoring

#90 [FEAT#70] Dockerfile_release dockerfile for release
  Dockerfile_release
Labels: :sparkles: Feature

#104 [Feat] add web configuration
  src/main/java/com/lckback/lckforall/base/config/WebConfiguration.java
Labels: :sparkles: Feature

#110 [Refactor#109] modify code related refresh path
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
Labels: :recycle: Refactoring

#108 [CD#103] Deployment 깃허브 액션 타겟 브랜치 수정
  .github/workflows/Deployment.yml
Labels: :hammer: Fix

#113 Fix/#112 fix swagger authorization error
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckMatchController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckPlayerController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckTeamController.java
  src/main/java/com/lckback/lckforall/base/setting/SwaggerConfig.java
Labels: :hammer: Fix

#119 [Refactor#116] swagger pageable처리 및 api tag, opertaion 추가 (커스텀 어노테이션 활용)
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckMatchController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckPlayerController.java
  src/main/java/com/lckback/lckforall/aboutlck/controller/AboutLckTeamController.java
  src/main/java/com/lckback/lckforall/base/setting/SwaggerPageable.java
Labels: :memo: documentation, :recycle: Refactoring

#118 [Refactor/#117] my page : specify return type
  src/main/java/com/lckback/lckforall/base/api/ApiResponse.java
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
Labels: :recycle: Refactoring

#121 [Refactor/#120]: apply `@SecurityRequirement`, `@SwaggerPageable`
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
Labels: :recycle: Refactoring

#123 [Refactor#122] add isCaptain field in SeasonTeamPlayer Entity
  src/main/java/com/lckback/lckforall/player/model/SeasonTeamPlayer.java
Labels: :recycle: Refactoring

#125 [Refactor/#114] modify auth swagger
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
Labels: :recycle: Refactoring

#127 refactor : 요구사항 추가에 따른Response 속성 추가, 채팅 기능 구체화
  src/main/java/com/lckback/lckforall/base/api/error/ChatErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/ViewingPartyErrorCode.java
  src/main/java/com/lckback/lckforall/viewing/controller/ChatController.java
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingController.java
  src/main/java/com/lckback/lckforall/viewing/converter/ChatConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChatDTO.java
  src/main/java/com/lckback/lckforall/viewing/dto/GetViewingPartyDetailDTO.java
  src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java
  src/main/java/com/lckback/lckforall/viewing/model/ChatRoom.java
  src/main/java/com/lckback/lckforall/viewing/model/Participate.java
  src/main/java/com/lckback/lckforall/viewing/repository/ChatRoomRepository.java
  src/main/java/com/lckback/lckforall/viewing/service/ChatService.java
  src/main/java/com/lckback/lckforall/viewing/service/ChatServiceImpl.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyService.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyServiceImpl.java
Labels: :memo: documentation, :sparkles: Feature, :recycle: Refactoring

#131 refactor : 뷰잉파티 엔티티 orphanRemoval 적용
  src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
Labels: :recycle: Refactoring

#128 [Feat] community 구현 #41
  src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java
  src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java
  src/main/java/com/lckback/lckforall/community/controller/CommentController.java
  src/main/java/com/lckback/lckforall/community/controller/PostController.java
  src/main/java/com/lckback/lckforall/community/dto/CommentDto.java
  src/main/java/com/lckback/lckforall/community/dto/PostDto.java
  src/main/java/com/lckback/lckforall/community/model/Post.java
  src/main/java/com/lckback/lckforall/community/model/PostFile.java
  src/main/java/com/lckback/lckforall/community/repository/PostFileRepository.java
  src/main/java/com/lckback/lckforall/community/repository/PostRepository.java
  src/main/java/com/lckback/lckforall/community/repository/PostTypeRepository.java
  src/main/java/com/lckback/lckforall/community/service/CommentService.java
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :sparkles: Feature

#134 [Refactor/#129] add api to check duplicate nickname
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/dto/GetNicknameDto.java
  src/main/java/com/lckback/lckforall/base/auth/jwt/JWTFilter.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
  src/main/java/com/lckback/lckforall/base/config/SecurityConfig.java
  src/main/java/com/lckback/lckforall/user/model/User.java
Labels: :sparkles: Feature, :recycle: Refactoring

#138 [Refactor/#136] modify code related to user tier
  src/main/java/com/lckback/lckforall/user/converter/SignupUserDataConverter.java
  src/main/java/com/lckback/lckforall/user/dto/SignupUserDataDto.java
  src/main/java/com/lckback/lckforall/user/model/User.java
Labels: :recycle: Refactoring

#143 [refactor/#142] 뷰잉파티 리스트 조회, 뷰잉파티 상세조회 주소정보 수정
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
Labels: :recycle: Refactoring

#144 release 0.0.2
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ViewingPartyListDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
Labels: :recycle: Refactoring

#146 [refactor/#145] 뷰잉파티 리스트에서 보일 짧은 주소 필드 추가
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java
  src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
Labels: :recycle: Refactoring

#148 release 0.0.3
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java
  src/main/java/com/lckback/lckforall/viewing/model/ViewingParty.java
Labels: :recycle: Refactoring

#149 [Feat/#147] community add report api
  src/main/java/com/lckback/lckforall/base/api/error/CommentErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java
  src/main/java/com/lckback/lckforall/report/controller/CommentReportController.java
  src/main/java/com/lckback/lckforall/report/controller/PostReportController.java
  src/main/java/com/lckback/lckforall/report/repository/CommentReportRepository.java
  src/main/java/com/lckback/lckforall/report/repository/PostReportRepository.java
  src/main/java/com/lckback/lckforall/report/service/CommentReportService.java
  src/main/java/com/lckback/lckforall/report/service/PostReportService.java
Labels: :sparkles: Feature

#151 [Refactor/#150] aboutlck edit response date to time
  src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckMatchService.java
Labels: :recycle: Refactoring, :hammer: Fix

#153 [Refactor#152] : modify Entity for url length
  src/main/java/com/lckback/lckforall/player/model/Player.java
  src/main/java/com/lckback/lckforall/team/model/Team.java
Labels: :recycle: Refactoring

#157 [Fix#156] fix today's match date logic
  src/main/java/com/lckback/lckforall/match/service/MatchService.java
Labels: :hammer: Fix

#155 [refactoring] swagger 관련 사항 수정
  src/main/java/com/lckback/lckforall/match/controller/HomeController.java
  src/main/java/com/lckback/lckforall/match/controller/MatchController.java
  src/main/java/com/lckback/lckforall/match/controller/PogController.java
  src/main/java/com/lckback/lckforall/vote/controller/VoteController.java
Labels: :recycle: Refactoring

#160 [refactor/#159] 뷰잉파티 리스트에서 보일 짧은 주소 update 로직 수정
  src/main/java/com/lckback/lckforall/base/auth/controller/AuthController.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
  src/main/java/com/lckback/lckforall/viewing/controller/ViewingChangeController.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChangeViewingPartyDTO.java
  src/main/java/com/lckback/lckforall/viewing/dto/GetViewingPartyDetailDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyChangeServiceImpl.java
Labels: :recycle: Refactoring

#162 [Refactor/#161] about lck modify response
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerInformationConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamPlayerInformationDto.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckPlayerService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
  src/main/java/com/lckback/lckforall/base/api/error/SeasonErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/SeasonTeamErrorCode.java
Labels: :recycle: Refactoring

#164 [fix] home화면 오류 수정
  src/main/java/com/lckback/lckforall/match/service/HomeService.java
Labels: :hammer: Fix

#171 [Refactor/#170] 뷰잉파티 Request, Reponse DTO 포맷팅 로직 구현
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
Labels: :recycle: Refactoring

#172 release 0.0.6
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyChangeConverter.java
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
Labels: :recycle: Refactoring

#174 [Refactor#173] : modify match detail dto field
  src/main/java/com/lckback/lckforall/aboutlck/converter/match/AboutMatchConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/match/FindMatchesByDateDto.java
Labels: :recycle: Refactoring

#176 [Refactor]: update form-data key name
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
Labels: :recycle: Refactoring

#181 [Refactor/#180] 뷰잉파티 참여자 목록조회 Response DTO 필드 추가
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ViewingPartyServiceImpl.java
Labels: :recycle: Refactoring

#184 [refactor/#183] 채팅기록 조회 API Response 필드 추가
  src/main/java/com/lckback/lckforall/viewing/converter/ChatConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChatDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ChatServiceImpl.java
Labels: :recycle: Refactoring

#185 release 0.0.10
  src/main/java/com/lckback/lckforall/viewing/converter/ChatConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ChatDTO.java
  src/main/java/com/lckback/lckforall/viewing/service/ChatServiceImpl.java
Labels: :recycle: Refactoring

#186 Feat/#41 community update
  src/main/java/com/lckback/lckforall/base/api/error/CommentErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java
  src/main/java/com/lckback/lckforall/community/controller/CommentController.java
  src/main/java/com/lckback/lckforall/community/controller/PostController.java
  src/main/java/com/lckback/lckforall/community/dto/CommentDto.java
  src/main/java/com/lckback/lckforall/community/dto/PostDto.java
  src/main/java/com/lckback/lckforall/community/model/Comment.java
  src/main/java/com/lckback/lckforall/community/model/Post.java
  src/main/java/com/lckback/lckforall/community/model/PostFile.java
  src/main/java/com/lckback/lckforall/community/model/PostType.java
  src/main/java/com/lckback/lckforall/community/repository/CommentRepository.java
  src/main/java/com/lckback/lckforall/community/repository/PostFileRepository.java
  src/main/java/com/lckback/lckforall/community/service/CommentService.java
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :sparkles: Feature

#187 release 0.0.11
  src/main/java/com/lckback/lckforall/base/api/error/CommentErrorCode.java
  src/main/java/com/lckback/lckforall/base/api/error/PostErrorCode.java
  src/main/java/com/lckback/lckforall/community/controller/CommentController.java
  src/main/java/com/lckback/lckforall/community/controller/PostController.java
  src/main/java/com/lckback/lckforall/community/dto/CommentDto.java
  src/main/java/com/lckback/lckforall/community/dto/PostDto.java
  src/main/java/com/lckback/lckforall/community/model/Comment.java
  src/main/java/com/lckback/lckforall/community/model/Post.java
  src/main/java/com/lckback/lckforall/community/model/PostFile.java
  src/main/java/com/lckback/lckforall/community/model/PostType.java
  src/main/java/com/lckback/lckforall/community/repository/CommentRepository.java
  src/main/java/com/lckback/lckforall/community/repository/PostFileRepository.java
  src/main/java/com/lckback/lckforall/community/service/CommentService.java
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :sparkles: Feature

#188 [Refactor] : MyPage
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/dto/GetUserProfileDto.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
Labels: :recycle: Refactoring

#190 [Feat] 매치 별 set count api 추가 + 프런트 요청 사항에 따른 수정
  src/main/java/com/lckback/lckforall/base/api/error/VoteErrorCode.java
  src/main/java/com/lckback/lckforall/match/controller/MatchController.java
  src/main/java/com/lckback/lckforall/match/dto/MatchInfoDto.java
  src/main/java/com/lckback/lckforall/match/service/MatchService.java
  src/main/java/com/lckback/lckforall/match/service/PogService.java
Labels: :sparkles: Feature

#193 [Refactor/#192] about lck team modify dto to display captain
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerInformationConverter.java
  src/main/java/com/lckback/lckforall/aboutlck/dto/team/FindTeamPlayerInformationDto.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
Labels: :recycle: Refactoring

#196 [Refactor#195] : modify postlist dto return value
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :recycle: Refactoring

#198 refactor: CommentDto.CommentDetailDto getTeamName으로수정
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :recycle: Refactoring

#203 [Refactor#202] about lck team - modify converter logic
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
Labels: :recycle: Refactoring

#206 [Refactor#205] remove filter in converter
  src/main/java/com/lckback/lckforall/aboutlck/converter/team/FindTeamPlayerHistoryConverter.java
Labels: :recycle: Refactoring

#209 [Refactor]: return post sort by createdAt
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :recycle: Refactoring

#217 [refactor/#216] 참여자 조회 API Response 필드 추가
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java
Labels: :recycle: Refactoring

#218 release 0.0.23
  src/main/java/com/lckback/lckforall/viewing/converter/ViewingPartyConverter.java
  src/main/java/com/lckback/lckforall/viewing/dto/ParticipantListDTO.java
Labels: :recycle: Refactoring

#219 [Refactor] withdrawal
  src/main/java/com/lckback/lckforall/mypage/controller/MyPageController.java
  src/main/java/com/lckback/lckforall/mypage/service/MyPageService.java
  src/main/java/com/lckback/lckforall/user/model/User.java
Labels: :recycle: Refactoring

#221 [refactoring] drop vote constraint for demoday
  src/main/java/com/lckback/lckforall/match/service/PogService.java
  src/main/java/com/lckback/lckforall/vote/service/VoteService.java
Labels: :recycle: Refactoring

#224 [Refactor#223] Modify DTO and postService logic
  src/main/java/com/lckback/lckforall/community/dto/PostDto.java
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :recycle: Refactoring

#225 release 0.0.26
  src/main/java/com/lckback/lckforall/community/dto/PostDto.java
  src/main/java/com/lckback/lckforall/community/service/PostService.java
Labels: :recycle: Refactoring

#229 [refactor/#228] 로그인/회원가입시 사용자의 닉네임 반환
  src/main/java/com/lckback/lckforall/base/auth/converter/AuthResponseConverter.java
  src/main/java/com/lckback/lckforall/base/auth/dto/AuthResponseDto.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
Labels: :recycle: Refactoring

#230 release 0.0.27
  src/main/java/com/lckback/lckforall/base/auth/converter/AuthResponseConverter.java
  src/main/java/com/lckback/lckforall/base/auth/dto/AuthResponseDto.java
  src/main/java/com/lckback/lckforall/base/auth/service/AuthService.java
Labels: :tada: CI/CD, :recycle: Refactoring

#227 [Refactor/#226] about lck team filtering current season in winning history
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckPlayerService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
  src/main/java/com/lckback/lckforall/team/repository/SeasonTeamRepository.java
Labels: :recycle: Refactoring

#232 release 0.0.28
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckPlayerService.java
  src/main/java/com/lckback/lckforall/aboutlck/service/AboutLckTeamService.java
  src/main/java/com/lckback/lckforall/team/repository/SeasonTeamRepository.java
Labels: :recycle: Refactoring

#234 [Refactor#233] add @PostConstruct for modify timezone
  src/main/java/com/lckback/lckforall/LckForAllApplication.java
Labels: :recycle: Refactoring

#235 release 0.0.29
  src/main/java/com/lckback/lckforall/LckForAllApplication.java
Labels: :recycle: Refactoring
